In [32]:
import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dropout,Dense,Flatten,AveragePooling2D,Input
from tensorflow.keras.preprocessing.image import ImageDataGenerator,img_to_array,load_img
import matplotlib.pyplot as plt

In [24]:
img = ImageDataGenerator(rotation_range=0.3,
                        width_shift_range=0.1,height_shift_range=0.1,
                        zoom_range=0.2,shear_range=0.2,horizontal_flip=True,
                        fill_mode='nearest',rescale=1/255.0)

In [25]:
train_img = img.flow_from_directory('D:\\Python\\CNN\\Face Mask\\Train',target_size=(224,224),class_mode = 'binary')

Found 17553 images belonging to 2 classes.


In [26]:
test_img = img.flow_from_directory('D:\\Python\\CNN\\Face Mask\\Test',target_size=(224,224),class_mode = 'binary')

Found 992 images belonging to 2 classes.


In [28]:
base = MobileNetV2(input_shape=(224,224,3),include_top=False,weights='imagenet')

for layer in base.layers:
    layer.trainable = False

head = base.output
head = AveragePooling2D(7)(head)
head = Flatten()(head)
head = Dense(128,activation='relu')(head)
head = Dropout(0.2)(head)
head = Dense(1,activation='sigmoid')(head)

model = Model(inputs = base.input, outputs = head)

model.summary()

Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_11 (InputLayer)           [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 112, 112, 32) 864         input_11[0][0]                   
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 112, 112, 32) 128         Conv1[0][0]                      
__________________________________________________________________________________________________
Conv1_relu (ReLU)               (None, 112, 112, 32) 0           bn_Conv1[0][0]                   
____________________________________________________________________________________________

In [29]:
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])

In [31]:
model.fit(train_img,
         epochs=10,
         batch_size=64,
         verbose=2,
         validation_data=(test_img))

Epoch 1/10
549/549 - 301s - loss: 0.0424 - accuracy: 0.9837 - val_loss: 0.0365 - val_accuracy: 0.9909
Epoch 2/10
549/549 - 209s - loss: 0.0276 - accuracy: 0.9899 - val_loss: 0.0291 - val_accuracy: 0.9899
Epoch 3/10
549/549 - 208s - loss: 0.0261 - accuracy: 0.9905 - val_loss: 0.0232 - val_accuracy: 0.9909
Epoch 4/10
549/549 - 204s - loss: 0.0241 - accuracy: 0.9918 - val_loss: 0.0320 - val_accuracy: 0.9879
Epoch 5/10
549/549 - 204s - loss: 0.0221 - accuracy: 0.9909 - val_loss: 0.0147 - val_accuracy: 0.9950
Epoch 6/10
549/549 - 206s - loss: 0.0206 - accuracy: 0.9933 - val_loss: 0.0203 - val_accuracy: 0.9940
Epoch 7/10
549/549 - 214s - loss: 0.0178 - accuracy: 0.9934 - val_loss: 0.0111 - val_accuracy: 0.9929
Epoch 8/10
549/549 - 217s - loss: 0.0151 - accuracy: 0.9944 - val_loss: 0.0148 - val_accuracy: 0.9929
Epoch 9/10
549/549 - 226s - loss: 0.0153 - accuracy: 0.9946 - val_loss: 0.0169 - val_accuracy: 0.9960
Epoch 10/10
549/549 - 206s - loss: 0.0139 - accuracy: 0.9950 - val_loss: 0.0192 - 

In [33]:
model.save('Face_Mask.h5')

In [36]:
img = load_img("D:\\tests\\wm.jpg",target_size=(224,224))

In [37]:
img = img_to_array(img,dtype='float32')
img = img.reshape(1,224,224,3)/255.0

In [45]:
model.predict(img)

array([[0.99982977]], dtype=float32)

In [46]:
img = load_img("D:\\tests\\mask.jpg",target_size=(224,224))

In [47]:
img = img_to_array(img,dtype='float32')
img = img.reshape(1,224,224,3)/255.0

In [48]:
model.predict(img)

array([[6.472341e-05]], dtype=float32)

In [52]:
if model.predict(img) > 0.8:
    print('Mask')

In [56]:
img = load_img("D:\\tests\\woman.jpg",target_size=(224,224))
img = img_to_array(img,dtype='float32')
img = img.reshape(1,224,224,3)/255.0
model.predict(img)

array([[0.95598066]], dtype=float32)

In [57]:
img = load_img("D:\\tests\\w_mask.jpg",target_size=(224,224))
img = img_to_array(img,dtype='float32')
img = img.reshape(1,224,224,3)/255.0
model.predict(img)

array([[0.02109165]], dtype=float32)

In [59]:
img = load_img("D:\\tests\\test.jpg",target_size=(224,224))
img = img_to_array(img,dtype='float32')
img = img.reshape(1,224,224,3)/255.0
model.predict(img)

array([[0.12758592]], dtype=float32)

In [60]:
img = load_img("D:\\tests\\test1.jpg",target_size=(224,224))
img = img_to_array(img,dtype='float32')
img = img.reshape(1,224,224,3)/255.0
model.predict(img)

array([[2.344568e-05]], dtype=float32)

In [61]:
img = load_img("D:\\tests\\without.jpg",target_size=(224,224))
img = img_to_array(img,dtype='float32')
img = img.reshape(1,224,224,3)/255.0
model.predict(img)

array([[0.9956137]], dtype=float32)